trigger:
  branches:
    include:
      - main
      - feature

pool:
  name: pardeeppooljuly

stages:
- stage: Terraform
  jobs:
  - job: InfraCostJob

    steps:

    - checkout: self

    # ======================
    # TERRAFORM INIT
    # ======================
    - task: PowerShell@2
      displayName: Terraform Init
      inputs:
        targetType: inline
        script: |
          terraform init

    # ======================
    # TERRAFORM PLAN (CLI ONLY)
    # ======================
    - task: PowerShell@2
      displayName: Terraform Plan
      inputs:
        targetType: inline
        script: |
          terraform plan -out=tfplan

          if (!(Test-Path tfplan)) {
            Write-Error "tfplan not created"
            exit 1
          }

    # ======================
    # CONVERT PLAN TO JSON
    # ======================
    - task: PowerShell@2
      displayName: Convert Plan to JSON
      inputs:
        targetType: inline
        script: |
          terraform show -json tfplan > plan.json

          Get-Content plan.json | Select-Object -First 20

    # ======================
    # INSTALL INFRACOST
    # ======================
    - task: InfracostSetup@2
      inputs:
        apiKey: "ico-crAo3mJC3kRm7RoJF258WuLcT9q9yg5b"
        version: '0.10.x'

    # ======================
    # RUN INFRACOST
    # ======================
    - task: PowerShell@2
      displayName: Infracost Breakdown
      inputs:
        targetType: inline
        script: |
          infracost breakdown --path plan.json --format table