trigger:
 branches:
   include:
     - main
     - feature 

pool: 
 name: pardeeppooljuly

stages:
  - stage: 
    jobs:
      - job: "Terraforminit"
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'shashi'
            backendAzureRmOverrideSubscriptionID: '3a0a2930-e46e-4582-83fa-e3b55ea22da6'
            backendAzureRmResourceGroupName: 'rg001'
            backendAzureRmStorageAccountName: 'stg5592'
            backendAzureRmContainerName: 'container5592'
            backendAzureRmKey: 'terraform.tfstate'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'validate'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            environmentServiceNameAzureRM: 'shashi'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'apply'
            environmentServiceNameAzureRM: 'shashi'